[tool.pyright]
# Include directories for Pyright to check
include = ["apps"]

# Set Python interpreter from virtual environment
pythonPath = "~/Documents/Projects/frappe/eef-erp/env/bin/python"

# Set Python version (assuming Python 3.12 from venv)
pythonVersion = "3.12"

# Pyright settings
typeCheckingMode = "standard"