"""
This type stub file was generated by pyright.
"""

import typing

class _dict(dict):
    """dict like object that exposes keys as attributes"""
    def __getattr__(self, name: str) -> typing.Any:
        ...
    
    def __setattr__(self, name: str, value: typing.Any) -> None:
        ...
    
    def __delattr__(self, name: str) -> None:
        ...
    
    def __setstate__(self, state: typing.Mapping) -> None:
        ...
    
    def __getstate__(self) -> typing.Mapping:
        ...
    
    def update(self, *args: typing.Any, **kwargs: typing.Any) -> None:
        ...
    
    def copy(self) -> _dict:
        ...



